# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 19:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('category', models.CharField(default='', max_length=30)),
                ('social_id', models.CharField(max_length=100, null=True)),
                ('friendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friend',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=30)),
                ('message', models.TextField(default='')),
                ('time', models.DateTimeField(default=None)),
                ('social_id', models.CharField(max_length=100, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Friend')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_name', models.CharField(default='', max_length=30)),
                ('fb_token', models.TextField(default='')),
                ('fb_id', models.TextField(default='')),
                ('twitter_name', models.CharField(default='', max_length=30)),
                ('resource_owner_key', models.TextField(default='')),
                ('resource_owner_secret', models.TextField(default='')),
                ('twitter_id', models.TextField(default='')),
                ('last_query', models.DateTimeField(null=True)),
                ('last_fetch', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together=set([('user',)]),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set([('category', 'social_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set([('category', 'social_id')]),
        ),
    ]
