# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('time', models.DateTimeField(default=None)),
                ('loc', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'facebook_msg',
            },
        ),
        migrations.CreateModel(
            name='TwitterMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('time', models.DateTimeField(default=None)),
                ('loc', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'twitter_msg',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('passwd', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
                ('name', models.CharField(default='', max_length=30)),
                ('passwd', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'user_record',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userrecord',
            unique_together=set([('name',)]),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main_app.UserRecord'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main_app.UserRecord'),
        ),
        migrations.AddField(
            model_name='twittermsg',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.UserRecord'),
        ),
        migrations.AddField(
            model_name='facebookmsg',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.UserRecord'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('name',)]),
        ),
    ]
