# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
                ('name', models.CharField(default='', max_length=30)),
                ('passwd', models.CharField(default='', max_length=30)),
            ],
            options={
                'db_table': 'user_record',
            },
        ),
        migrations.AddField(
            model_name='facebookmsg',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='facebookmsg',
            name='loc',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='facebookmsg',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='twittermsg',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='twittermsg',
            name='loc',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='twittermsg',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='passwd',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('name',)]),
        ),
        migrations.AlterModelTable(
            name='facebookmsg',
            table='facebook_msg',
        ),
        migrations.AlterModelTable(
            name='twittermsg',
            table='twitter_msg',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterUniqueTogether(
            name='userrecord',
            unique_together=set([('name',)]),
        ),
        migrations.AddField(
            model_name='facebookmsg',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.UserRecord'),
        ),
        migrations.AddField(
            model_name='twittermsg',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.UserRecord'),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main_app.UserRecord'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main_app.UserRecord'),
        ),
    ]
