# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebookmessage',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='facebookmessage',
            name='loc',
        ),
        migrations.AddField(
            model_name='facebookmessage',
            name='page_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fb_last_fetch',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_last_fetch',
            field=models.DateTimeField(null=True),
        ),
    ]
