# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20160507_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='twitter_token',
            new_name='fb_id',
        ),
        migrations.AddField(
            model_name='friend',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resource_owner_key',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resource_owner_secret',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_id',
            field=models.TextField(default=''),
        ),
    ]
