# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20160409_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookmsg',
            name='time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='twittermsg',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.UserRecord'),
        ),
        migrations.AlterField(
            model_name='twittermsg',
            name='time',
            field=models.DateTimeField(default=None),
        ),
    ]
