# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_friend_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='img',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='friend',
            name='tag',
            field=models.CharField(default='other', max_length=50),
        ),
    ]
