# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20160409_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookmsg',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.UserRecord'),
        ),
    ]
