# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20160512_1531'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set([('category', 'social_id', 'friendee')]),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=set([('category', 'social_id', 'owner')]),
        ),
    ]
